# Generated by Django 5.2.13 on 2026-05-02 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customer',
            new_name='orders_cust_email_e97b09_idx',
            old_name='orders_cust_email_1b7db0_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_status_c6dd84_idx',
            old_name='orders_orde_status_d62e8c_idx',
        ),
    ]
