# Generated by Django 5.2.13 on 2026-05-02 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_action_86e815_idx',
            old_name='audit_audi_action_f3c7aa_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_entity_845d0e_idx',
            old_name='audit_audi_entity_4f7a5f_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_created_2c1626_idx',
            old_name='audit_audi_created_f14540_idx',
        ),
    ]
