# Generated by Django 5.2.13 on 2026-05-02 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='catalog_pro_sku_2c4c34_idx',
            old_name='catalog_pro_sku_34491b_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='catalog_pro_is_acti_14fc6b_idx',
            old_name='catalog_pro_is_acti_9ac066_idx',
        ),
    ]
